#!/usr/bin/perl

use strict;

my $file_name = "report.txt";
open(my $fh, '>>', $file_name);
print $fh "My first report generated by perl\n";
print $fh "My second report generated by perl\n";
close $fh;

print "done\n";

open(DATA, "<test.pl") or die "Couldn't open file test.pl, $!";

while(<DATA>){
	print "$_";
}
